# Generated by Django 3.0.14 on 2022-12-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('surname', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Фамилия клиента')),
                ('name', models.CharField(max_length=15, verbose_name='Имя клиента')),
                ('birthdate', models.DateField(verbose_name='Дата рождения клиента')),
                ('phonenumber', models.CharField(max_length=12, verbose_name='Номер телефона клиента')),
                ('gender', models.CharField(max_length=5, verbose_name='Пол клиента')),
                ('document', models.CharField(max_length=15, verbose_name='Тип документа')),
                ('document_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('document_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='RoomsCategory',
            fields=[
                ('room', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Номер комнаты')),
                ('category', models.CharField(max_length=10, verbose_name='Категория номера')),
                ('apartement', models.CharField(max_length=1, verbose_name='Количество комнат')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Категории Номера',
                'verbose_name_plural': 'Категории номеров',
            },
        ),
        migrations.CreateModel(
            name='RoomsCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(verbose_name='Дата приезда')),
                ('checkout', models.DateField(verbose_name='Дата отъезда')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Clients', verbose_name='Клиент')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.RoomsCategory', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Состояние Номера',
                'verbose_name_plural': 'Состояние Номеров',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Clients', verbose_name='Клиент')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.RoomsCategory', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
    ]
