# Generated by Django 3.0.14 on 2022-12-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221223_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='room_category',
        ),
        migrations.RemoveField(
            model_name='employess',
            name='employee_name',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_form',
            field=models.CharField(max_length=20, verbose_name='Форма оплаты'),
        ),
    ]
